# [START app_yaml]
runtime: nodejs14
# beta_settings:
#   cloud_sql_instances: instance_conn_name
env_variables:
  NODE_ENV: production
  DB_INSTANCE_NAME: /cloudsql/cosmic-quarter-326513:europe-north1:sports-db
  DB_PASSWORD: sports-db-pass-1
  DB_USER: sports-db
  DB_NAME: sports_db