### login new admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

#----------------------------------------- products

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/2

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjIyNjAsImV4cCI6MTYzMzM2MzE2MH0.P3JA0G3BuUPJGvkGs7dLEBaZOn672Pv43DUNvkWa95I

{
  "name": "new_p",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}

###
DELETE http://localhost:3000/api/products/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjIyNjAsImV4cCI6MTYzMzM2MzE2MH0.P3JA0G3BuUPJGvkGs7dLEBaZOn672Pv43DUNvkWa95I

###
PUT http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjIyNjAsImV4cCI6MTYzMzM2MzE2MH0.P3JA0G3BuUPJGvkGs7dLEBaZOn672Pv43DUNvkWa95I

{
  "id": "18",
  "name": "NEW_pp",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}

#----------------------------------------- trainer comments
###
POST http://localhost:3000/api/trainer/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjQzMjUsImV4cCI6MTYzMzM2NTIyNX0.5Y9bH75_Fo8BHZQLlrc3LSoKsTVJtJ4t2w24a6H-nBs

{
    "trainerId": "1",
    "comment": "HeDner"
}

###
GET http://localhost:3000/api/trainer/1/comments

###
PUT http://localhost:3000/api/trainer/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjM2NjMsImV4cCI6MTYzMzM2NDU2M30.wnNUw4JE_qgbJPeKEyHKsmZRGrfaYPOdgqnC_02smqI

{
  "commentId": "9",
  "comment": "goodbyeee"
}

###
DELETE http://localhost:3000/api/trainer/comments/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxMjozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDEyOjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzMzNjQzMjUsImV4cCI6MTYzMzM2NTIyNX0.5Y9bH75_Fo8BHZQLlrc3LSoKsTVJtJ4t2w24a6H-nBs

#----------------------------------------- trainer ratings
###
POST http://localhost:3000/api/trainer/rating
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTksIm5hbWUiOiJKaW0iLCJzdXJuYW1lIjoiamltbXkiLCJlbWFpbCI6ImFqaW0tZWFhbS5ydSIsInBhc3N3b3JkIjoiJDJiJDEwJGI5OWgwUzVwN2V2dnlydm9pa2xTSi5DZm1KblBFekZxNkU1N1lWNGdtTlJJWEo5NmdTUWFpIiwicmVnX2RhdGUiOiIyMDIxLTEwLTAyVDIyOjI5OjQ4LjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMDJUMjI6Mjk6NDguMDAwWiIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzMyMTM3OTYsImV4cCI6MTYzMzIxNDY5Nn0.xU-KmejuWYjhJntrqCWa52VmwBCDQ0mWzNmAq7vlXTg

{
    "trainerId": "2",
    "rating": "5"
}

###
GET http://localhost:3000/api/trainer/2/rating

### PUT 

### DELETE
