###
GET http://localhost:3000/api/trainers/2

###
GET http://localhost:3000/api/trainers/

#-----------------------------------------
### get posts
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTgsIm5hbWUiOiJKaW0iLCJzdXJuYW1lIjoiamltbXkiLCJlbWFpbCI6ImppbS1lYWFtLnJ1IiwicGFzc3dvcmQiOiIkMmIkMTAkdGN2QlpGZFVieW4yMnQwN2UwLjdJdVZvM2xhYWJYUmsxM1oyT0pyYXBwRkJsYkJhNmh2R20iLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjMzMTk4OTM0LCJleHAiOjE2MzMxOTk4MzR9.WznzJ4XIMIBtOHx8b3CbabCG0c4HCV4-PSd5SgpNSeA

### sigup  new user
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "name": "Jim",
    "surname": "jimmy",
    "email": "jim-eaam.ru",
    "password": "jimm"
}

### login new user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "jim-eaam.ru",
    "password": "jimm"
}

#-----------------------------------------

### login admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### admin get all users
GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk4OTYyLCJleHAiOjE2MzMxOTk4NjJ9.LYzhQP7okD4tWGvVr7RRVKyL6_iNVw_BGaJ4odQIeTQ

### admin get user
GET http://localhost:3000/api/users/98
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk4OTYyLCJleHAiOjE2MzMxOTk4NjJ9.LYzhQP7okD4tWGvVr7RRVKyL6_iNVw_BGaJ4odQIeTQ

### admin delete user
DELETE http://localhost:3000/api/users/98
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk4OTYyLCJleHAiOjE2MzMxOTk4NjJ9.LYzhQP7okD4tWGvVr7RRVKyL6_iNVw_BGaJ4odQIeTQ

#-----------------------------------------
### 
POST http://localhost:3000/api/users/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk5MzI4LCJleHAiOjE2MzMyMDI5Mjh9.08dg3fsV2nB99k8DwkzS1MzQsUjg_-vBg8qN-i4TxH0"
}

### logout
DELETE  http://localhost:3000/api/users/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk5MzI4LCJleHAiOjE2MzMyMDI5Mjh9.08dg3fsV2nB99k8DwkzS1MzQsUjg_-vBg8qN-i4TxH0"
}

#-----------------------------------------

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/15

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk4OTYyLCJleHAiOjE2MzMxOTk4NjJ9.LYzhQP7okD4tWGvVr7RRVKyL6_iNVw_BGaJ4odQIeTQ

{
  "name": "KKK",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}

###
DELETE http://localhost:3000/api/products/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMTk4OTYyLCJleHAiOjE2MzMxOTk4NjJ9.LYzhQP7okD4tWGvVr7RRVKyL6_iNVw_BGaJ4odQIeTQ

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsIsnR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMyMzQzOTkzLCJleHAiOjE2MzIzNDQ4OTN9.tR2UBCimjZGVHTmWPmtLSwonwavtKAoRkT6s1hCkXAw

{
  "id": "3",
  "name": "NAME",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}

#-----------------------------------------
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "jim-eaam.ru",
    "password": "jimm"
}

###
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMjA0NTQwLCJleHAiOjE2MzMyMDU0NDB9.alLOGWE9aAjLgCaxlwa--fxIxbTYQxJrkSwY46sCy84

{
    "productId": "1",
    "quantity": "1"
}

###
GET http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkTi42N1lKMG9NVnFZdFE0bFJ6T1h1Q0Z5ckZHbjU3REZHd3lhblpvOERGQ2VIYjhUbWE5QyIsInJlZ19kYXRlIjoiMjAyMS0wOS0yMFQxNzoxNjoxMC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTAyVDE3OjUyOjEzLjAwMFoiLCJtb25leSI6MzAwLjUsInJvbGUiOjI1NSwiaWF0IjoxNjMzMjA0NTQwLCJleHAiOjE2MzMyMDU0NDB9.alLOGWE9aAjLgCaxlwa--fxIxbTYQxJrkSwY46sCy84

###
POST http://localhost:3000/api/trainer/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTgsIm5hbWUiOiJKaW0iLCJzdXJuYW1lIjoiamltbXkiLCJlbWFpbCI6ImppbS1lYWFtLnJ1IiwicGFzc3dvcmQiOiIkMmIkMTAkdGN2QlpGZFVieW4yMnQwN2UwLjdJdVZvM2xhYWJYUmsxM1oyT0pyYXBwRkJsYkJhNmh2R20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDJUMTg6MjE6MzguMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0wMlQxOTo0Nzo1OS4wMDBaIiwibW9uZXkiOjU3OC45NCwicm9sZSI6MSwiaWF0IjoxNjMzMjA4MjQwLCJleHAiOjE2MzMyMDkxNDB9.Unc28n5d745T819766JnKrtUVTpHtH4m9TfT088v-0M

{
    "trainerId": "2",
    "comment": "Hello trainer"
}

###
POST http://localhost:3000/api/trainer/rating
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTgsIm5hbWUiOiJKaW0iLCJzdXJuYW1lIjoiamltbXkiLCJlbWFpbCI6ImppbS1lYWFtLnJ1IiwicGFzc3dvcmQiOiIkMmIkMTAkdGN2QlpGZFVieW4yMnQwN2UwLjdJdVZvM2xhYWJYUmsxM1oyT0pyYXBwRkJsYkJhNmh2R20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDJUMTg6MjE6MzguMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0wMlQxOTo0Nzo1OS4wMDBaIiwibW9uZXkiOjU3OC45NCwicm9sZSI6MSwiaWF0IjoxNjMzMjA5NDUzLCJleHAiOjE2MzMyMTAzNTN9.FfuyRjpfRoZaozxjKg2By-XJ7SkX0Yz0glRyFaOK3qY

{
    "trainerId": "1",
    "rating": "3.6"
}
