GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwic3VybmFtZSI6Im5ldy1zdXJuIiwiZW1haWwiOiJuZXctbWFpbC5ydSIsInBhc3N3b3JkIjoiJDJiJDEwJDFRenk0bHhUL2gvTXREWDN1Q3RMbGVld1pzWjJaSWVnRS5lZVJ6M0NHaVdlSzRRZXhRUjFDIiwiaWF0IjoxNjMxOTg1ODIyLCJleHAiOjE2MzE5ODY0MjJ9.UivTyGubYW-SmA2XbWRngh9Kr-HSJEeetiY8-7p8oHU

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Kyle"
}

###
GET http://localhost:3000/trainers/2

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "Jim",
    "surname": "new-surn",
    "email": "new-mail.ru",
    "password": "asdasd"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "new-mail.ru",
    "password": "asdasd"
}