GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IadskpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzMTk4MDI5MywiZXhwIjoxNjMxOTgwODkzfQ.YpoRM-syj0-n3xc6R289Ufc9hljctWgWZZn9bn49pcU

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}

###
GET http://localhost:3000/trainers/2