###
GET http://cosmic-quarter-326513.appspot.com/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTIwMTU0LCJleHAiOjE2MzQ5MjczNTR9.4oH-fsjjWkZ2zWax4VHLqZSBtoM0kQSymHKlYKTYq9E

### 
POST http://cosmic-quarter-326513.appspot.com/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTIwMTU0LCJleHAiOjE2MzQ5MjczNTR9.4oH-fsjjWkZ2zWax4VHLqZSBtoM0kQSymHKlYKTYq9E

{
    "productId": 24,
    "quantity": 1
}

###
PUT http://cosmic-quarter-326513.appspot.com/api/orders/24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTIwMTU0LCJleHAiOjE2MzQ5MjczNTR9.4oH-fsjjWkZ2zWax4VHLqZSBtoM0kQSymHKlYKTYq9E

{
    "productId": 14,
    "quantity": 4
}

###
DELETE  http://cosmic-quarter-326513.appspot.com/api/orders/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTIwMTU0LCJleHAiOjE2MzQ5MjczNTR9.4oH-fsjjWkZ2zWax4VHLqZSBtoM0kQSymHKlYKTYq9E
