#----------------------------------------- trainer ratings
###
GET http://cosmic-quarter-326513.appspot.com/api/ratings

###
GET http://cosmic-quarter-326513.appspot.com/api/trainers/5/ratings

###
GET http://cosmic-quarter-326513.appspot.com/api/trainers/5/ratings/average

###
POST http://cosmic-quarter-326513.appspot.com/api/trainers/5/ratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDRUMTI6Mzk6MzEuMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0yMlQxMDo0MDowOS4wMDBaIiwibW9uZXkiOjEwMDAsInJvbGUiOjI1NSwiaWF0IjoxNjM0OTE4MjI1LCJleHAiOjE2MzQ5MjU0MjV9.afs4eEW4_XOHh5e0gw4C_HkAREPeh4VkcBesiiAjZ88

{
    "rating": 2.56
}

###
PUT http://cosmic-quarter-326513.appspot.com/api/trainers/5/ratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDRUMTI6Mzk6MzEuMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0yMlQxMDo0MDowOS4wMDBaIiwibW9uZXkiOjEwMDAsInJvbGUiOjI1NSwiaWF0IjoxNjM0OTE4MjI1LCJleHAiOjE2MzQ5MjU0MjV9.afs4eEW4_XOHh5e0gw4C_HkAREPeh4VkcBesiiAjZ88

{
    "rating": 1.123
}

###
DELETE http://cosmic-quarter-326513.appspot.com/api/trainers/5/ratings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDRUMTI6Mzk6MzEuMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0yMlQxMDo0MDowOS4wMDBaIiwibW9uZXkiOjEwMDAsInJvbGUiOjI1NSwiaWF0IjoxNjM0OTE4MjI1LCJleHAiOjE2MzQ5MjU0MjV9.afs4eEW4_XOHh5e0gw4C_HkAREPeh4VkcBesiiAjZ88
