###
GET http://localhost:3000/api/trainers/2/

###
GET http://localhost:3000/api/trainers/

#-----------------------------------------
### sigun  new user
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "name": "Jim",
    "surname": "new-surn",
    "email": "new-mail.ru",
    "password": "admin"
}

### login new user
POST http://localhost:3000/api/users/login/asd
Content-Type: application/json

{
    "email": "new-mail.ru",
    "password": "asdasd"
}

#-----------------------------------------

### login admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### admin get all users
GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMzMzU3NTM3LCJleHAiOjE2MzMzNTg0Mzd9.0q71KS4LGyog5cQmautB9cUf5RdS-wJcv2L_3XnzsXA

### admin delete user
DELETE http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMyMzQyNDA0LCJleHAiOjE2MzIzNDMzMDR9.kgCwBXyI0gcV24C9N0RduK5oiMwP7zAt4LxyP5ZhagM

#-----------------------------------------

### login admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

### 
POST http://localhost:3000/api/users/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMzMzU3Nzc1LCJleHAiOjE2MzMzNjEzNzV9.yhr0XQoxiMWjPbAINUrMpNeffGWKGSyWN9RXPvkmZ_U"
}

### logout admin
DELETE  http://localhost:3000/api/users/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMzMzU3Nzc1LCJleHAiOjE2MzMzNjEzNzV9.yhr0XQoxiMWjPbAINUrMpNeffGWKGSyWN9RXPvkmZ_U"
}


#-----------------------------------------
### login admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/1

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMyODU3MTYwLCJleHAiOjE2MzI4NTgwNjB9.sUQUu_nK7Sy5sGjQm3yHCIVVBw43e74SRJLLz6xd7ps

{
  "name": "ad_prod",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}

###
DELETE http://localhost:3000/api/products/34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMzMzYwMDgyLCJleHAiOjE2MzMzNjA5ODJ9.HAJQSOHkp8vDcB9S_Sj6N5A0ephVUmPpv2gItffzd8k

###
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJuYW1lIjoiQURNSU4iLCJzdXJuYW1lIjoiQURNSU5fUyIsImVtYWlsIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCQ2SE9UczJaWk1IUDRUcUVlQnhJUzlPYTJyZTEwYkVJN0lWbTFqT3dzNm02Zy8xUkJZWnM3dSIsIm1vbmV5Ijo5OTkuOTksInJvbGUiOjI1NSwiaWF0IjoxNjMzMzYwMDgyLCJleHAiOjE2MzMzNjA5ODJ9.HAJQSOHkp8vDcB9S_Sj6N5A0ephVUmPpv2gItffzd8k

{
  "id": "3",
  "name": "new_name",
  "description": "A can of beans",
  "price": 2.34,
  "quantity": 5
}