# #----------------------------------------- login users
# ### sigup  new user
# POST http://localhost:3000/api/users/signup
# Content-Type: application/json

# {
#     "name": "Jim",
#     "surname": "Jimmerson",
#     "email": "neww-mail.ru",
#     "password": "admin"
# }

# ### login user
# POST http://localhost:3000/api/users/login
# Content-Type: application/json

# {
#     "email": "my-email.com",
#     "password": "N"
# }

# ### login admin
# POST http://localhost:3000/api/users/login
# Content-Type: application/json

# {
#     "email": "admin@admin.com",
#     "password": "admin"
# }

# ### refresh token
# POST http://localhost:3000/api/users/refresh
# Content-Type: application/json

# {
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRWMEhoZ2hXVUc5UmVHUEYuVXBvbVFPYUtibFdrM2U5dU9WOTBsd1Yxemlhd2RVeUJjTm94VyIsImlhdCI6MTYzNDQ3Nzk1OSwiZXhwIjoxNjM0NDgxNTU5fQ.4kqb1lh6As0xZX_4CRPcVnkvNLp8fY6Q0Oj0ISuNxgk"
# }

# ### logout user
# DELETE  http://localhost:3000/api/users/logout
# Content-Type: application/json

# {
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsImlhdCI6MTYzNDQ3Nzk0NywiZXhwIjoxNjM0NDgxNTQ3fQ.i86_oETPhSWM5MJ-Sfr6Fl3EtjyCX9ZBYvz8-_zQyPw"
# }

# #----------------------------------------- manage users

# ### admin get all users
# GET http://localhost:3000/api/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkppbSIsInN1cm5hbWUiOiJKaW1tZXJzb24iLCJlbWFpbCI6Im5ldy1tYWlsLnJ1IiwicmVnX2RhdGUiOiIyMDIxLTEwLTE2VDExOjIyOjQyLjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMTZUMTE6MjI6NDIuMDAwWiIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzQ0Nzg2MDUsImV4cCI6MTYzNDQ4NTgwNX0.olCQT7BgqwcjMyU2jXlA4a_-HMm-QN7YzHy1tBMA2j0

# ### user or admin get user details
# GET http://localhost:3000/api/users/14
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJBbHZ5ZGFzIiwic3VybmFtZSI6IkRPUyIsImVtYWlsIjoibXktZW1haWwuY29tIiwicmVnX2RhdGUiOiIyMDIxLTEwLTE3VDEwOjMyOjQ0LjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMTdUMTE6MjA6MTUuMDAwWiIsIm1vbmV5Ijo3NzcsInJvbGUiOjYsImlhdCI6MTYzNDQ4MDQzMiwiZXhwIjoxNjM0NDg3NjMyfQ.wXJS1ApFBWysZXKEGFlkhrso2T9GvjKWoyUULU1uVU8

# ### admin update user
# PUT http://localhost:3000/api/users/14
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyZWdfZGF0ZSI6IjIwMjEtMTAtMDRUMTI6Mzk6MzEuMDAwWiIsIm1vZGlmeV9kYXRlIjoiMjAyMS0xMC0wNFQxMjo0MDoxNS4wMDBaIiwibW9uZXkiOjAsInJvbGUiOjI1NSwiaWF0IjoxNjM0NDgwMjU3LCJleHAiOjE2MzQ0ODc0NTd9.iyAZ84hjo69ulSCbPGPSm_J7lpf1vzkuj8RZ8GXZpZI

# {
#   "name": "Alvydas",
#   "surname": "DOS",
#   "email": "mya-email.com",
#   "money": 777,
#   "role": 6
# }

# ### user update user
# PUT http://localhost:3000/api/users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJBbHZ5ZGFzIiwic3VybmFtZSI6IkRPUyIsImVtYWlsIjoibXlhLWVtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0xN1QxMDozMjo0NC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTE3VDExOjIxOjEwLjAwMFoiLCJtb25leSI6Nzc3LCJyb2xlIjo2LCJpYXQiOjE2MzQ0ODEzNDgsImV4cCI6MTYzNDQ4ODU0OH0.s4KFItxcGmlAcpd2IbQ5LrDb5IEOt406fEffn4Vd_PY

# {
#   "name": "AASAS",
#   "surname": "DOS",
#   "password": "N",
#   "email": "my-email.com"
# }


# ### admin delete user
# DELETE http://localhost:3000/api/users/6
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJBbHZ5ZGFzIiwic3VybmFtZSI6IkRPUyIsImVtYWlsIjoibXlhLWVtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0xN1QxMDozMjo0NC4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTE3VDExOjIxOjEwLjAwMFoiLCJtb25leSI6Nzc3LCJyb2xlIjo2LCJpYXQiOjE2MzQ0ODEzNDgsImV4cCI6MTYzNDQ4ODU0OH0.s4KFItxcGmlAcpd2IbQ5LrDb5IEOt406fEffn4Vd_PY

# #----------------------------------------- products
# ###
# GET http://cosmic-quarter-326513.appspot.com/api/products

# ###
# GET http://cosmic-quarter-326513.appspot.com/api/products/32

# ###
# POST http://cosmic-quarter-326513.appspot.com/api/products
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#   "name": "NEW NAME",
#   "description": "A can of beans",
#   "price": 2.34,
#   "quantity": 55
# }

# ###
# PUT http://cosmic-quarter-326513.appspot.com/api/products/32
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#   "name": "NEWER NAME",
#   "description": "Mr bean",
#   "price": 56.8,
#   "quantity": 5
# }

# ###
# DELETE http://cosmic-quarter-326513.appspot.com/api/products/33
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI


# #----------------------------------------- trainer comments
# ###
# GET http://cosmic-quarter-326513.appspot.com/api/trainers/1/comments

# ###
# POST http://cosmic-quarter-326513.appspot.com/api/trainers/1/comments
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#     "comment": "new comment for trainer 1"
# }

# ###
# PUT http://cosmic-quarter-326513.appspot.com/api/trainers/comments/20
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#   "comment": "wrong"
# }

# ###
# DELETE http://cosmic-quarter-326513.appspot.com/api/trainers/comments/21
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# #----------------------------------------- trainer ratings
# ###
# GET http://cosmic-quarter-326513.appspot.com/api/ratings

# ###
# GET http://cosmic-quarter-326513.appspot.com/api/trainers/1/ratings

# ###
# GET http://cosmic-quarter-326513.appspot.com/api/trainers/1/ratings/average

# ###
# POST http://cosmic-quarter-326513.appspot.com/api/trainers/1/ratings
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#     "rating": 2.69
# }

# ###
# PUT http://cosmic-quarter-326513.appspot.com/api/trainers/1/ratings
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

# {
#     "rating": 3.55
# }

# ###
# DELETE http://cosmic-quarter-326513.appspot.com/api/trainers/1/ratings
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRyaHVPY0UuQkxGb2xsakFzSDJXcGRlY0FOUHJHR2xOb1hvdVMwemJoeXNWMXpZd2c0ZS5UYSIsInJlZ19kYXRlIjoiMjAyMS0xMC0wNFQxNTozOTozMS4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTA0VDE1OjQwOjE1LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MjU1LCJpYXQiOjE2MzM4MDQyMzcsImV4cCI6MTYzMzgwNTEzN30.dvFuxdvW7iGJOKqEoLmQh-UpxYv8VQkc77P_0LVM-MI

#----------------------------------------- orders
### ~~~

# #----------------------------------------- trainers
# ### ~~~
# ###
# GET http://localhost:3000/api/trainers/2/

# ###
# GET http://localhost:3000/api/trainers/
