#----------------------------------------- trainer comments
###
GET http://localhost:3000/api/trainers/6/comments

###
POST http://localhost:3000/api/trainers/6/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

{
    "comment": "EEEE"
}

###
PUT http://localhost:3000/api/trainers/comments/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

{
  "comment": "GEEE"
}

###
DELETE http://localhost:3000/api/trainers/comments/26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM
