###
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksIm5hbWUiOiJLeWxlIiwic3VybmFtZSI6IkppbW1lcnNvbiIsImVtYWlsIjoibmV3dy1tYWlsLnJ1IiwicmVnX2RhdGUiOiIyMDIxLTEwLTE3VDEyOjE0OjU5LjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMTdUMTI6MTQ6NTkuMDAwWiIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzQ5MDk5NDEsImV4cCI6MTYzNDkxNzE0MX0.MfR7ZDjUTwYVbQBT_AI406UMu1Ts18ZYoDdwfGYowuc

###
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksIm5hbWUiOiJLeWxlIiwic3VybmFtZSI6IkppbW1lcnNvbiIsImVtYWlsIjoibmV3dy1tYWlsLnJ1IiwicmVnX2RhdGUiOiIyMDIxLTEwLTE3VDEyOjE0OjU5LjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMTdUMTI6MTQ6NTkuMDAwWiIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzQ5MDk5NDEsImV4cCI6MTYzNDkxNzE0MX0.MfR7ZDjUTwYVbQBT_AI406UMu1Ts18ZYoDdwfGYowuc

{
    "productId": 37,
    "quantity": 2
}

###
PUT http://localhost:3000/api/orders/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksIm5hbWUiOiJLeWxlIiwic3VybmFtZSI6IkppbW1lcnNvbiIsImVtYWlsIjoibmV3dy1tYWlsLnJ1IiwicmVnX2RhdGUiOiIyMDIxLTEwLTE3VDEyOjE0OjU5LjAwMFoiLCJtb2RpZnlfZGF0ZSI6IjIwMjEtMTAtMTdUMTI6MTQ6NTkuMDAwWiIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzQ5MDk5NDEsImV4cCI6MTYzNDkxNzE0MX0.MfR7ZDjUTwYVbQBT_AI406UMu1Ts18ZYoDdwfGYowuc

{
    "quantity": 4
}