### sigup  new user
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "name": "John",
    "surname": "Smith",
    "email": "john@gmail.com",
    "password": "John"
}

### login user
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "John"
}

### login admin
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### refresh token
POST http://localhost:3000/api/users/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjQ4OjU3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE3ODMxLCJleHAiOjE2MzQ5MjE0MzF9.mBOgANJoG8UnKigjX2bxKg8tmcxTa2s5mbqUbqasETA"
}

### logout user
DELETE  http://localhost:3000/api/users/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsIm1vbmV5IjowLCJyb2xlIjoxLCJpYXQiOjE2MzQ5MTc4MzQsImV4cCI6MTYzNDkyMTQzNH0.HDAsNX2GXffbv6zg_3pV4PH_CtXlb8e1rbphrNQR6Vk"
}

#----------------------------------------- manage users

### user get details
GET http://localhost:3000/api/users/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM


### admin get all users
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

### admin
GET http://localhost:3000/api/users/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

### admin update user
PUT http://localhost:3000/api/users/19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

{
  "name": "Alvydas",
  "surname": "AL",
  "email": "myaa-email.com",
  "money": 777,
  "role": 6
}

### user update user
PUT http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM

{
  "name": "John",
  "surname": "Smith",
  "email": "john@gmail.com"
}


### admin delete user
DELETE http://localhost:3000/api/users/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWUiOiJKb2huIiwic3VybmFtZSI6IlNtaXRoIiwiZW1haWwiOiJqb2huQGdtYWlsLmNvbSIsInJlZ19kYXRlIjoiMjAyMS0xMC0yMlQxMjo0ODo1Ny4wMDBaIiwibW9kaWZ5X2RhdGUiOiIyMDIxLTEwLTIyVDEyOjU2OjM3LjAwMFoiLCJtb25leSI6MCwicm9sZSI6MSwiaWF0IjoxNjM0OTE5NTAwLCJleHAiOjE2MzQ5MjY3MDB9.Iq6qxg2WV8d5XzkKxQ4qZsavYL3IXm6r-CY31oHkMKM
